<?php

namespace Database\Seeders;

use App\Domains\Chatbot\Models\ChatbotPergunta;
use Illuminate\Database\Seeder;

class ChatbotPerguntasSeeder extends Seeder
{
    public function run(): void
    {
        $perguntas = $this->getPerguntas();

        foreach ($perguntas as $ordem => $p) {
            ChatbotPergunta::updateOrCreate(
                ['pergunta' => $p['pergunta']],
                [
                    'resposta' => $p['resposta'],
                    'palavras_chave' => $p['palavras_chave'],
                    'role_filter' => $p['role_filter'],
                    'ordem' => $ordem + 1,
                    'activa' => true,
                ]
            );
        }

        $this->command->info('Seeded ' . count($perguntas) . ' perguntas no chatbot.');
    }

    /**
     * @return array<int, array{pergunta: string, resposta: string, palavras_chave: array, role_filter: array}>
     */
    private function getPerguntas(): array
    {
        return [
            // ============ 1. PAGAMENTOS & TAXAS (20) ============
            [
                'pergunta' => 'Como pago a minha taxa de condomínio?',
                'resposta' => 'Vai a Extracto, escolhe o lançamento e clica em Pagar. Tens 3 opções: ProxyPay (referência), comprovativo manual (foto), ou usar saldo de créditos.',
                'palavras_chave' => ['pagar', 'pagamento', 'taxa', 'quota', 'como pagar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'O que é o ProxyPay?',
                'resposta' => 'É o sistema oficial de referências bancárias em Angola. Quando pagas com ProxyPay, recebes uma referência de 9 dígitos que usas no Multicaixa Express ou na tua aplicação bancária. O pagamento é confirmado automaticamente.',
                'palavras_chave' => ['proxypay', 'referência', 'multicaixa', 'rps'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como envio comprovativo de transferência?',
                'resposta' => 'Em Extracto, escolhe Pagar e depois Comprovativo manual. Carrega foto ou PDF do comprovativo. O gestor vai validar e marcar como pago.',
                'palavras_chave' => ['comprovativo', 'transferência', 'recibo', 'enviar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Quanto tempo demora a confirmação do pagamento?',
                'resposta' => 'ProxyPay: automático em 5 minutos. Comprovativo manual: depende da validação do gestor (normalmente 24h úteis).',
                'palavras_chave' => ['confirmação', 'tempo', 'demora', 'quando'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'O que é o Fundo de Reserva?',
                'resposta' => 'É um valor adicional cobrado mensalmente (junto da taxa) para obras e despesas extraordinárias do condomínio. É obrigatório por lei (Decreto 141/15, Art. 7).',
                'palavras_chave' => ['fundo', 'reserva', 'obras', 'extraordinário'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como vejo os meus pagamentos anteriores?',
                'resposta' => 'Vai a Pagamentos. Vês todos os teus pagamentos (confirmados, pendentes, rejeitados). Clica em qualquer um para ver detalhes.',
                'palavras_chave' => ['histórico', 'anteriores', 'pagamentos', 'ver'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'O que acontece se pagar com atraso?',
                'resposta' => 'Se o condomínio tem multas configuradas, fica automaticamente uma multa por mora. O valor depende do que está definido (percentual ou valor fixo). Vê em Configuração e depois Multas.',
                'palavras_chave' => ['atraso', 'multa', 'mora', 'tarde'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'O meu pagamento foi rejeitado, e agora?',
                'resposta' => 'Vai a Pagamentos, escolhe o pagamento rejeitado e vê o motivo indicado pelo gestor. Corrige o problema (ex: foto ilegível) e submete novamente.',
                'palavras_chave' => ['rejeitado', 'recusado', 'erro', 'motivo'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'O que são créditos da fracção?',
                'resposta' => 'Saldo positivo do teu imóvel. Acumula quando pagas a mais, há reembolso ou conversão. Podes usar créditos em pagamentos futuros, evitando ter que transferir dinheiro novo.',
                'palavras_chave' => ['créditos', 'saldo', 'positivo', 'imóvel'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como uso os meus créditos para pagar?',
                'resposta' => 'No painel de Pagamento, se tiveres créditos disponíveis, vais ver opção Aplicar a lançamento com saldo disponível. Escolhes o lançamento e o valor.',
                'palavras_chave' => ['créditos', 'usar', 'aplicar', 'saldo'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como vejo quanto devo no total?',
                'resposta' => 'Em Extracto, no topo, tens Total em dívida — soma todos os teus lançamentos em aberto. Em vermelho se tiver atraso.',
                'palavras_chave' => ['dívida', 'total', 'devo', 'extracto'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso pagar várias taxas de uma vez?',
                'resposta' => 'Sim. Quando carregas em Pagar num lançamento, podes na coluna direita aplicar o pagamento a múltiplos lançamentos em aberto. O valor distribui-se conforme escolhas.',
                'palavras_chave' => ['várias', 'multiplos', 'vez', 'distribuir'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como gerar taxas mensais para todos os imóveis?',
                'resposta' => 'Vai a Taxas e clica em Gerar Taxas. Selecciona o mês e o sistema cria automaticamente lançamentos para cada imóvel (taxa base + fundo de reserva), com valores conforme configuração.',
                'palavras_chave' => ['gerar', 'taxas', 'mensal', 'automático'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como confirmo um pagamento por comprovativo manual?',
                'resposta' => 'Em Pagamentos, escolhe pagamento pendente, vê comprovativo e escolhe Confirmar ou Rejeitar com motivo.',
                'palavras_chave' => ['confirmar', 'aprovar', 'validar', 'comprovativo'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Posso reverter um pagamento confirmado?',
                'resposta' => 'Sim. Em Pagamentos, escolhe pagamento confirmado e clica em Reverter. As aplicações desfazem-se, lançamentos voltam ao estado original. Útil em caso de erro ou devolução.',
                'palavras_chave' => ['reverter', 'cancelar', 'desfazer', 'erro'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como criar um lançamento manual?',
                'resposta' => 'Vai a Lançamentos e clica em Novo lançamento. Escolhe tipo (despesa extra, multa, ajuste), imóvel(eis), descrição e valor. Podes lançar para várias fracções de uma vez.',
                'palavras_chave' => ['lançamento', 'manual', 'despesa', 'criar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como cancelo um lançamento criado por engano?',
                'resposta' => 'Em Lançamentos, escolhe o lançamento e clica em Cancelar. Indica motivo. Se já tem pagamentos aplicados, primeiro reverte os pagamentos.',
                'palavras_chave' => ['cancelar', 'apagar', 'remover', 'lançamento'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'A app aceita pagamento em Kwanzas?',
                'resposta' => 'Sim, todas as taxas e pagamentos são em Kwanzas (Kz), moeda oficial de Angola. ONDAKA é feito especificamente para o mercado angolano.',
                'palavras_chave' => ['kwanzas', 'moeda', 'kz', 'angola'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como exportar relatório de pagamentos?',
                'resposta' => 'Vai a Pagamentos, filtra por período/estado e clica em Exportar (PDF ou Excel). Podes partilhar com a contabilidade ou auditoria.',
                'palavras_chave' => ['exportar', 'relatório', 'excel', 'pdf'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Posso ver pagamentos de outros condóminos?',
                'resposta' => 'Apenas o gestor e o administrador do condomínio têm acesso a todos os pagamentos. Cada condómino só vê os seus próprios.',
                'palavras_chave' => ['privacidade', 'outros', 'ver', 'acesso'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Que significa "Quota proporcional" no meu imóvel?',
                'resposta' => 'É a percentagem do edifício que pertence ao teu imóvel (em milésimas — ‰). Define quanto pagas no total das despesas comuns. Exemplo: se a tua quota é 25‰, pagas 2,5% do orçamento do condomínio.',
                'palavras_chave' => ['quota proporcional', 'permilagem', 'milésimas', 'percentagem'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como adiciono um novo imóvel ao condomínio?',
                'resposta' => 'Vai a Imóveis e clica em Novo imóvel. Indica identificador (ex: 2B), área, quota proporcional (‰), taxa base mensal e fundo de reserva mensal.',
                'palavras_chave' => ['novo', 'imóvel', 'adicionar', 'criar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como alterar valores de taxa de um imóvel?',
                'resposta' => 'Vai a Imóveis, escolhe o imóvel e clica em Editar. Ajusta Taxas de Condomínio mensais (Kz). Os novos valores aplicam-se às próximas gerações de taxas.',
                'palavras_chave' => ['alterar', 'editar', 'valor', 'taxa'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como associar um condómino a um imóvel?',
                'resposta' => 'Vai a Condóminos, escolhe o condómino e clica em Associar imóvel. Selecciona o imóvel e tipo de relação (proprietário, inquilino).',
                'palavras_chave' => ['associar', 'condómino', 'contrato', 'proprietário'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Qual a diferença entre proprietário e inquilino?',
                'resposta' => 'O proprietário é o dono do imóvel, responsável final pelas taxas. O inquilino arrenda. No ONDAKA podes definir se as taxas são pagas por um ou outro.',
                'palavras_chave' => ['proprietário', 'inquilino', 'arrendatário', 'dono'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Quantos imóveis posso ter associados?',
                'resposta' => 'Como condómino, podes ter vários imóveis associados (ex: apartamento + estacionamento + arrumo). Vês todos no menu lateral e podes alternar entre eles.',
                'palavras_chave' => ['vários', 'múltiplos', 'limite', 'quantos'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como ver detalhes de um imóvel?',
                'resposta' => 'Vai a Imóveis e escolhe o imóvel. Vês: identificador, área (m²), quota proporcional, taxas mensais, e condómino(s) associado(s).',
                'palavras_chave' => ['detalhes', 'ver', 'imóvel', 'informação'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'A soma das quotas proporcionais do edifício é sempre 1000‰?',
                'resposta' => 'Sim, deve ser exactamente 1000‰ (100%). O ONDAKA mostra um aviso se a soma estiver desalinhada para corrigires.',
                'palavras_chave' => ['soma', 'total', '1000', 'milésimas'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Posso eliminar um imóvel?',
                'resposta' => 'Não recomendado se o imóvel tiver lançamentos, pagamentos ou histórico. Se for mesmo necessário, contacta o gestor — ele pode desactivar em vez de eliminar.',
                'palavras_chave' => ['eliminar', 'apagar', 'remover', 'desactivar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como vejo todos os imóveis do edifício?',
                'resposta' => 'Vai a Edifícios, escolhe o edifício e vês a lista de imóveis com identificadores, áreas e estado de cada um.',
                'palavras_chave' => ['edifício', 'lista', 'todos', 'imóveis'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como criar um novo edifício no condomínio?',
                'resposta' => 'Vai a Condomínios, escolhe o condomínio, depois Edifícios e Novo edifício. Indica nome (ex: Torre A), número de pisos e descrição.',
                'palavras_chave' => ['novo', 'edifício', 'torre', 'criar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como mudar de condomínio activo (gestor com vários)?',
                'resposta' => 'No topo da app, clica no seletor de condomínio (lado esquerdo do header). Aparece lista dos condomínios que geres — escolhe o que queres ver.',
                'palavras_chave' => ['mudar', 'alternar', 'condomínio', 'trocar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como abro um pedido de intervenção?',
                'resposta' => 'Vai a Pedidos e clica em Novo pedido. Escreve título (ex: Fuga de água na cave), descrição detalhada, escolhe categoria (canalização, eléctrico, etc.) e prioridade. Podes anexar fotos.',
                'palavras_chave' => ['abrir', 'criar', 'pedido', 'intervenção'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como anexar fotos a um pedido?',
                'resposta' => 'No formulário de novo pedido, há um botão Adicionar foto. Podes carregar várias imagens (do telemóvel ou da câmara). Ajuda muito o gestor a perceber o problema.',
                'palavras_chave' => ['foto', 'imagem', 'anexar', 'câmara'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Quais são os estados possíveis de um pedido?',
                'resposta' => 'Em ordem: Aberto (acabaste de criar), Em análise (gestor a avaliar), Em curso (a ser resolvido), Resolvido (concluído), Fechado (arquivado), ou Cancelado.',
                'palavras_chave' => ['estado', 'status', 'pedido', 'situação'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como sei quem está a tratar do meu pedido?',
                'resposta' => 'Em Pedidos, escolhe o teu pedido e vê secção Atribuído a. Se não tem ninguém, ainda não foi atribuído. O gestor é avisado e atribui em pouco tempo.',
                'palavras_chave' => ['atribuído', 'responsável', 'tratar', 'quem'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como comentar num pedido?',
                'resposta' => 'Abre o pedido. No fundo, há campo Adicionar comentário. Escreve e clica em Enviar. Todos os intervenientes (condómino, gestor, prestador) recebem aviso.',
                'palavras_chave' => ['comentar', 'comentário', 'responder', 'mensagem'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Quais são as prioridades disponíveis?',
                'resposta' => 'Baixa (pode esperar), Normal (assunto regular), Alta (precisa atenção rápida), Urgente (resolver hoje, ex: fuga grave). Não abuses de Urgente — perde efeito.',
                'palavras_chave' => ['prioridade', 'urgente', 'importante', 'grave'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como atribuir um pedido a um prestador?',
                'resposta' => 'Em Pedidos, escolhe o pedido e na secção Atribuir escolhe da lista de utilizadores (gestor, funcionário, prestador). Quando atribuíres, o utilizador recebe notificação.',
                'palavras_chave' => ['atribuir', 'prestador', 'delegar', 'designar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como mudar o estado de um pedido?',
                'resposta' => 'Em Pedidos, escolhe pedido e no painel direito escolhe novo estado. Cada mudança é registada no histórico do pedido.',
                'palavras_chave' => ['mudar', 'alterar', 'estado', 'progresso'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Posso cancelar um pedido que abri?',
                'resposta' => 'Sim, enquanto estiver em Aberto ou Em análise. Em Pedidos, escolhe o teu pedido e clica em Cancelar pedido. Indica motivo.',
                'palavras_chave' => ['cancelar', 'desistir', 'remover', 'apagar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como vejo só os meus pedidos?',
                'resposta' => 'Em Pedidos usa o filtro Meus pedidos, ou na app mobile vai à tab Os meus pedidos.',
                'palavras_chave' => ['meus', 'filtro', 'só', 'pessoais'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Recebo notificação quando o meu pedido muda de estado?',
                'resposta' => 'Sim, automaticamente: por push notification (mobile), email (se configurado) e sino de notificações dentro da app.',
                'palavras_chave' => ['notificação', 'aviso', 'push', 'email'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Quais são as categorias de pedidos?',
                'resposta' => 'Canalização, Eléctrico, Pintura, Carpintaria, Limpeza, Segurança, Jardinagem, Outro. O gestor pode adicionar categorias específicas do condomínio em Configuração.',
                'palavras_chave' => ['categoria', 'tipo', 'canalização', 'eléctrico'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como exportar pedidos para relatório?',
                'resposta' => 'Em Pedidos, filtra por período/categoria/estado e clica em Exportar. Recebes PDF ou Excel com lista detalhada (útil para reuniões de assembleia).',
                'palavras_chave' => ['exportar', 'relatório', 'excel', 'pdf'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Posso ver pedidos antigos já fechados?',
                'resposta' => 'Sim. Em Pedidos usa o filtro Estado: Fechado. Histórico fica permanentemente disponível para consulta e auditoria.',
                'palavras_chave' => ['antigos', 'histórico', 'fechados', 'arquivo'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como dar feedback após resolução de um pedido?',
                'resposta' => 'Quando o pedido fica Resolvido, o sistema pede-te avaliação (1-5 estrelas) + comentário opcional. Ajuda o gestor a melhorar o serviço.',
                'palavras_chave' => ['avaliação', 'feedback', 'estrelas', 'opinião'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como pré-aprovar uma visita?',
                'resposta' => 'Vai a Visitantes, depois Pré-aprovação e Nova pré-aprovação. Indica nome do visitante, BI/passaporte, data e hora prevista, e duração esperada.',
                'palavras_chave' => ['pré-aprovar', 'visita', 'autorizar', 'visitante'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Para que serve a pré-aprovação de visitas?',
                'resposta' => 'Permite que o guarda da portaria reconheça o visitante quando chega, sem precisar de te ligar para confirmar. Mais rápido e seguro.',
                'palavras_chave' => ['para que', 'utilidade', 'porquê', 'benefício'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso pré-aprovar várias visitas de uma vez?',
                'resposta' => 'Sim. Cada pré-aprovação é individual mas podes criar várias seguidas. Para visitas recorrentes (ex: empregada doméstica), usa a opção Visitante recorrente.',
                'palavras_chave' => ['várias', 'múltiplas', 'recorrente', 'empregada'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Que acontece se a visita chegar fora do horário previsto?',
                'resposta' => 'A pré-aprovação tem uma tolerância configurável. Se a visita chegar muito antes ou depois, o guarda telefona ao condómino para confirmar.',
                'palavras_chave' => ['horário', 'atraso', 'fora', 'tolerância'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como cancelar uma pré-aprovação?',
                'resposta' => 'Vai a Pré-aprovações, escolhe a pré-aprovação e clica em Cancelar. O guarda fica avisado automaticamente.',
                'palavras_chave' => ['cancelar', 'desmarcar', 'remover', 'desistir'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como ver quem está dentro do condomínio agora (visitantes)?',
                'resposta' => 'Como guarda, vai a Portaria, depois Dentro agora. Vês lista de visitantes com check-in feito mas ainda sem check-out.',
                'palavras_chave' => ['dentro', 'presente', 'agora', 'portaria'],
                'role_filter' => ['funcionario'],
            ],
            [
                'pergunta' => 'Como faço check-in de uma visita?',
                'resposta' => 'Como guarda, vai a Portaria, depois Check-in. Pesquisa visitante (BI ou nome) ou usa pré-aprovação. Tira foto se necessário e regista entrada.',
                'palavras_chave' => ['check-in', 'entrada', 'registar', 'portaria'],
                'role_filter' => ['funcionario'],
            ],
            [
                'pergunta' => 'Como faço check-out de uma visita?',
                'resposta' => 'Em Portaria, depois Dentro agora, escolhe o visitante e clica em Check-out. A saída fica registada com hora exacta.',
                'palavras_chave' => ['check-out', 'saída', 'registar', 'portaria'],
                'role_filter' => ['funcionario'],
            ],
            [
                'pergunta' => 'O condómino é avisado quando a visita chega?',
                'resposta' => 'Sim, automaticamente por push notification e SMS (se configurado). Vê quem chegou e a que hora.',
                'palavras_chave' => ['aviso', 'notificação', 'chegou', 'sms'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como vejo histórico de visitas ao meu imóvel?',
                'resposta' => 'Vai a Visitantes, depois Histórico. Lista de todas as visitas com data, hora de entrada e saída, e duração. Filtros por período disponíveis.',
                'palavras_chave' => ['histórico', 'passado', 'visitas', 'anteriores'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso ter visitantes sem pré-aprovação?',
                'resposta' => 'Sim, mas o guarda terá de te ligar primeiro para confirmar. Pré-aprovação é mais conveniente — não atrasas o teu visitante.',
                'palavras_chave' => ['sem', 'obrigatório', 'livre', 'espontânea'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como adicionar uma pessoa autorizada permanente?',
                'resposta' => 'Para visitantes regulares (familiar, empregado, motorista), vai a Visitantes, depois Autorizados e Novo autorizado. Indica BI e foto. Ficam pré-aprovados sempre.',
                'palavras_chave' => ['autorizado', 'permanente', 'familiar', 'empregado'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso autorizar um visitante a recolher encomendas?',
                'resposta' => 'Sim. Quando criares um autorizado, marca a opção Pode levantar encomendas. O guarda só entrega encomendas a pessoas com esta permissão.',
                'palavras_chave' => ['encomenda', 'levantar', 'recolher', 'autorizado'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Os meus dados de visitantes são privados?',
                'resposta' => 'Sim. Apenas tu, o guarda em serviço e o gestor do condomínio vêem os teus visitantes. Outros condóminos não têm acesso.',
                'palavras_chave' => ['privacidade', 'privado', 'dados', 'acesso'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso ver lista de visitantes do condomínio inteiro (gestor)?',
                'resposta' => 'Sim, em Visitantes tens vista geral. Útil para auditoria de segurança ou em caso de incidente. Tens filtros por imóvel, período e nome.',
                'palavras_chave' => ['todos', 'geral', 'condomínio', 'auditoria'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como pré-anuncio uma encomenda que vai chegar?',
                'resposta' => 'Vai a Encomendas e clica em Novo pré-anúncio. Indica origem (Amazon, Loja X), número de tracking se tiveres, e estimativa de chegada. O guarda fica avisado.',
                'palavras_chave' => ['pré-anunciar', 'encomenda', 'chegar', 'avisar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Que acontece quando a encomenda chega à portaria?',
                'resposta' => 'O guarda regista a entrada, marca como Na portaria e tu recebes notificação. Tens um prazo para a recolher (configurável pelo gestor).',
                'palavras_chave' => ['chegou', 'portaria', 'recolher', 'levantar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como vejo as minhas encomendas pendentes?',
                'resposta' => 'Em Encomendas, na tab Aguardam chegada (pré-anunciadas) ou Na portaria (já chegaram).',
                'palavras_chave' => ['pendentes', 'minhas', 'aguardar', 'portaria'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso autorizar alguém a levantar a minha encomenda?',
                'resposta' => 'Sim. Vai a Visitantes e Autorizados. Cria autorização com a opção Pode levantar encomendas activa. Essa pessoa pode levantar em teu nome.',
                'palavras_chave' => ['autorizar', 'levantar', 'terceiro', 'delegar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como entregar uma encomenda (guarda)?',
                'resposta' => 'Em Portaria, depois Encomendas e Na portaria, escolhe a encomenda e clica em Entregar. Verifica BI da pessoa que está a recolher (deve ser o titular ou autorizado).',
                'palavras_chave' => ['entregar', 'recolher', 'guarda', 'portaria'],
                'role_filter' => ['funcionario'],
            ],
            [
                'pergunta' => 'Como registar uma encomenda manual (sem pré-anúncio)?',
                'resposta' => 'Em Portaria, clica em Registar manual. Escolhe imóvel destinatário (pesquisa), descreve a encomenda e tira foto se possível.',
                'palavras_chave' => ['manual', 'sem aviso', 'registar', 'surpresa'],
                'role_filter' => ['funcionario'],
            ],
            [
                'pergunta' => 'Quanto tempo posso deixar uma encomenda na portaria?',
                'resposta' => 'Depende da configuração do condomínio (normalmente 7-15 dias). Recebes lembretes. Após esse prazo, o gestor pode contactar-te para resolver.',
                'palavras_chave' => ['tempo', 'prazo', 'deixar', 'guardar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como ver histórico de encomendas?',
                'resposta' => 'Em Encomendas, na tab Histórico. Vês todas as encomendas anteriores (entregues, devolvidas) com datas e quem recebeu.',
                'palavras_chave' => ['histórico', 'passado', 'anteriores', 'arquivo'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'A foto da encomenda fica visível para mim?',
                'resposta' => 'Sim. Quando o guarda regista, podes ver a foto da encomenda em Na portaria para confirmares antes de descer a buscá-la.',
                'palavras_chave' => ['foto', 'imagem', 'ver', 'confirmar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Recebo aviso quando alguém recolhe a minha encomenda?',
                'resposta' => 'Sim. Push notification e/ou email com hora de recolha e nome de quem recolheu (titular ou autorizado).',
                'palavras_chave' => ['aviso', 'notificação', 'recolheu', 'retirou'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso recusar uma encomenda?',
                'resposta' => 'Sim. Em Encomendas e Na portaria, escolhe encomenda e clica em Recusar. Indica motivo. O guarda devolve ao estafeta ou trata da devolução.',
                'palavras_chave' => ['recusar', 'devolver', 'não quero', 'rejeitar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como configurar prazo de recolha de encomendas?',
                'resposta' => 'Vai a Configuração e Encomendas. Ajusta Prazo máximo de recolha (em dias). Escolhe também se queres lembretes automáticos para condóminos.',
                'palavras_chave' => ['prazo', 'configurar', 'dias', 'limite'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como sei se há assembleia marcada?',
                'resposta' => 'Vai a Assembleias. Vês todas as próximas e passadas. Quando há nova convocatória, recebes notificação por email + push + sino.',
                'palavras_chave' => ['próxima', 'marcada', 'data', 'quando'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como convocar uma assembleia?',
                'resposta' => 'Vai a Assembleias e Nova assembleia. Indica tipo (ordinária/extraordinária), data, hora, local, e ordem de trabalhos (pontos a discutir). Sistema envia convocatórias automaticamente.',
                'palavras_chave' => ['convocar', 'marcar', 'assembleia', 'criar'],
                'role_filter' => ['administrador-condominio'],
            ],
            [
                'pergunta' => 'Qual a antecedência mínima para convocar uma assembleia?',
                'resposta' => 'Pelo Decreto 141/15: 8 dias para ordinária, 4 dias para extraordinária. ONDAKA avisa-te se estiveres a convocar com menos antecedência.',
                'palavras_chave' => ['antecedência', 'prazo', 'decreto', 'convocar'],
                'role_filter' => ['administrador-condominio'],
            ],
            [
                'pergunta' => 'Como confirmo presença na assembleia?',
                'resposta' => 'Em Assembleias, escolhe a assembleia e clica em Confirmar presença. Podes confirmar até ao início da assembleia.',
                'palavras_chave' => ['presença', 'confirmar', 'vou', 'participar'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso votar à distância (sem ir à assembleia)?',
                'resposta' => 'Sim! ONDAKA permite voto remoto. Quando a assembleia tem ponto aberto a votação, qualquer condómino com login pode votar (Sim, Não, Abstenção) directamente da app.',
                'palavras_chave' => ['votar', 'distância', 'remoto', 'online'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como o meu voto é contado (peso)?',
                'resposta' => 'O voto é ponderado pela tua quota proporcional (‰). Um imóvel com 50‰ tem mais peso que um com 20‰. Sistema calcula automaticamente a maioria.',
                'palavras_chave' => ['peso', 'contado', 'milésimas', 'maioria'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como abrir uma votação durante a assembleia?',
                'resposta' => 'Em Assembleias, ver assembleia em curso, escolhe ponto e Abrir votação. Define duração. Sistema notifica todos os condóminos. Quando fechares, mostra resultados.',
                'palavras_chave' => ['abrir', 'votação', 'iniciar', 'assembleia'],
                'role_filter' => ['administrador-condominio'],
            ],
            [
                'pergunta' => 'Que é o quorum?',
                'resposta' => 'É a percentagem mínima de quotas presentes/representadas para a assembleia ser válida. Decreto 141/15 exige 50%+1‰ (maioria simples) em primeira convocatória. ONDAKA mostra o quorum em tempo real.',
                'palavras_chave' => ['quorum', 'presentes', 'válida', 'decreto'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como acedo à acta de uma assembleia?',
                'resposta' => 'Em Assembleias, escolhe a assembleia (terminada) e clica em Descarregar acta PDF. A acta é gerada automaticamente com decisões e votações.',
                'palavras_chave' => ['acta', 'pdf', 'descarregar', 'documento'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Posso delegar o meu voto a outro condómino?',
                'resposta' => 'Sim. Vai a Assembleias, escolhe assembleia e Delegar voto. Escolhe outro condómino. Ele vota no teu lugar com o teu peso de milésimas.',
                'palavras_chave' => ['delegar', 'procuração', 'representar', 'outro'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como vejo o resultado de uma votação?',
                'resposta' => 'Em Assembleias, escolhe ponto. Vês: total de Sim/Não/Abstenção, milésimas de cada lado, percentagens, e decisão (Aprovado / Rejeitado).',
                'palavras_chave' => ['resultado', 'votação', 'aprovado', 'decisão'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'A acta tem valor legal?',
                'resposta' => 'Sim. Conforme o Decreto 141/15, Art. 12, a acta da assembleia constitui título executivo para cobrança de quotas. Contém quórum, votações e decisões.',
                'palavras_chave' => ['legal', 'valor', 'título executivo', 'decreto'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Posso adicionar pontos à ordem do dia?',
                'resposta' => 'Como condómino, podes pedir ao administrador para adicionar pontos antes da assembleia ser convocada. Após convocada, só o administrador pode adicionar (com aprovação dos presentes).',
                'palavras_chave' => ['adicionar', 'ponto', 'ordem do dia', 'propor'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Quem assina a acta?',
                'resposta' => 'A acta é assinada pelo presidente da mesa e pelo secretário da assembleia. ONDAKA gera a acta digitalmente; assinatura física é feita à parte se necessário para arquivo.',
                'palavras_chave' => ['assinar', 'presidente', 'secretário', 'mesa'],
                'role_filter' => ['administrador-condominio'],
            ],
            [
                'pergunta' => 'Como ver assembleias passadas?',
                'resposta' => 'Em Assembleias usa filtro Realizadas. Vês listagem com data, número de participantes, e decisões principais. Acta PDF disponível para descarregar.',
                'palavras_chave' => ['passadas', 'históricas', 'anteriores', 'arquivo'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como envio um aviso a todos os condóminos?',
                'resposta' => 'Vai a Avisos e Novo aviso. Escreve título, conteúdo, escolhe destinatários (todos/segmentado) e canais (push, email). Podes anexar PDF.',
                'palavras_chave' => ['aviso', 'comunicado', 'enviar', 'todos'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como vejo avisos não lidos?',
                'resposta' => 'No topo da app, o sino com badge vermelho mostra avisos novos. Clica para ver lista. Em Avisos, filtra por Não lidos.',
                'palavras_chave' => ['não lido', 'novos', 'sino', 'notificação'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Posso comentar num aviso?',
                'resposta' => 'Depende: se o gestor activou comentários nesse aviso, sim. Vês o campo de comentário no fundo. Útil para perguntas rápidas que não justificam novo pedido.',
                'palavras_chave' => ['comentar', 'responder', 'comentário', 'discussão'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como segmentar um aviso (apenas alguns condóminos)?',
                'resposta' => 'No formulário de novo aviso e Destinatários, escolhe Segmentado. Filtra por edifício, piso, ou condóminos específicos. Útil para avisos que não interessam a todos.',
                'palavras_chave' => ['segmentar', 'filtrar', 'específico', 'só alguns'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Os avisos são enviados também por SMS?',
                'resposta' => 'Por defeito, não — para evitar custos. Mas o gestor pode activar SMS para avisos urgentes (consome créditos SMS da empresa gestora).',
                'palavras_chave' => ['sms', 'mensagem', 'telemóvel', 'urgente'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como anexar PDF a um aviso?',
                'resposta' => 'No formulário de novo aviso, secção Anexos, carrega ficheiro PDF (até 10MB). Útil para acta de reunião, regulamentos, orçamentos.',
                'palavras_chave' => ['anexo', 'pdf', 'documento', 'ficheiro'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Quem viu o meu aviso?',
                'resposta' => 'Vai a Avisos, escolhe o teu aviso e Estatísticas de leitura. Vês quem leu e quem não leu. Útil para garantir comunicação efectiva.',
                'palavras_chave' => ['leitura', 'quem viu', 'estatísticas', 'tracking'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Posso editar um aviso depois de enviar?',
                'resposta' => 'Pequenas correcções (typos): sim, em Avisos, escolher aviso e Editar. Mudanças grandes (mudar destinatários ou conteúdo): cria novo aviso para evitar confusão.',
                'palavras_chave' => ['editar', 'corrigir', 'alterar', 'depois'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como faço login no ONDAKA?',
                'resposta' => 'Vai a ondaka.ao ou abre a app mobile. Insere email + password. Se tiveres 2FA, recebes um código por SMS para confirmar.',
                'palavras_chave' => ['login', 'entrar', 'acesso', 'password'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Esqueci-me da password, e agora?',
                'resposta' => 'No login, clica em Esqueci-me da password. Insere o email — recebes link para criar nova password. Se não receberes, verifica spam ou contacta o gestor.',
                'palavras_chave' => ['esqueci', 'password', 'recuperar', 'reset'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como activar a autenticação de dois factores (2FA)?',
                'resposta' => 'Vai a Conta, depois Segurança e 2FA SMS. Confirma o teu telemóvel. A partir daí, cada login pede código SMS além da password.',
                'palavras_chave' => ['2fa', 'dois factores', 'sms', 'segurança'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como mudar a minha password?',
                'resposta' => 'Vai a Conta, depois Segurança e Alterar password. Insere password actual e nova (min. 8 caracteres). Por segurança, és deslogado de outros dispositivos.',
                'palavras_chave' => ['mudar', 'alterar', 'password', 'trocar'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como actualizar o meu telemóvel ou email?',
                'resposta' => 'Vai a Conta e Editar perfil. Altera o que precisares. Mudança de email requer confirmação por link enviado para o novo email.',
                'palavras_chave' => ['telemóvel', 'email', 'contacto', 'actualizar'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como adicionar foto de perfil?',
                'resposta' => 'Em Conta, Editar perfil, clica na foto/iniciais e Carregar imagem. Útil para o guarda te identificar facilmente.',
                'palavras_chave' => ['foto', 'perfil', 'avatar', 'imagem'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como sair (logout) da app?',
                'resposta' => 'No menu lateral, em baixo, clica em Sair (ícone de porta). Em mobile: Mais e Sair. Sessão fica terminada nesse dispositivo.',
                'palavras_chave' => ['sair', 'logout', 'terminar', 'desconectar'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Posso ter a mesma conta em vários dispositivos?',
                'resposta' => 'Sim. Faz login em quantos dispositivos quiseres (telemóvel, tablet, computador). Sessões mantêm-se activas em todos. Em Conta e Sessões vês onde estás logado.',
                'palavras_chave' => ['vários', 'dispositivos', 'multiplos', 'simultâneo'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como criar uma nova conta de utilizador?',
                'resposta' => 'Como gestor, vai a Condóminos e Novo condómino. Preenche dados (nome, BI, email, telemóvel). O sistema envia convite por email com link para o novo utilizador definir password.',
                'palavras_chave' => ['criar', 'conta', 'novo', 'condómino'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como bloquear/desbloquear um utilizador?',
                'resposta' => 'Em Condóminos, escolhe utilizador e usa o toggle Activo. Quando desactivado, não consegue fazer login até reactivares.',
                'palavras_chave' => ['bloquear', 'desactivar', 'suspender', 'activar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como ver as minhas sessões activas?',
                'resposta' => 'Vai a Conta, depois Segurança e Sessões activas. Lista todos os dispositivos onde estás logado (com IP, navegador, última actividade). Podes terminar sessões individualmente.',
                'palavras_chave' => ['sessões', 'activas', 'dispositivos', 'login'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'A app funciona offline?',
                'resposta' => 'Parcialmente. Podes ver dados já sincronizados (extracto, pedidos antigos) sem internet. Mas criar pedidos, pagar, ver novidades requer conexão. App sincroniza assim que volta online.',
                'palavras_chave' => ['offline', 'sem internet', 'sincronização', 'desconectado'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Onde fica a configuração de Facturação?',
                'resposta' => 'Vai a Facturação e Configuração. Tens 4 separadores: Coordenadas (NIF, IBAN), ProxyPay, Quotas (taxas mensais), Multas.',
                'palavras_chave' => ['configurar', 'facturação', 'definições', 'setup'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como configurar o NIF e IBAN do condomínio?',
                'resposta' => 'Em Facturação, Configuração e Coordenadas. Insere NIF, nome fiscal, IBAN, número de conta. Necessário para gerar facturas e mostrar dados nos comprovativos.',
                'palavras_chave' => ['nif', 'iban', 'conta', 'fiscal'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como activar o ProxyPay para o condomínio?',
                'resposta' => 'Em Facturação, Configuração e ProxyPay. Insere as credenciais (Entity ID, API Key) que recebeste da ProxyPay/banco. Activa o toggle. A partir daí, condóminos podem pagar com referência.',
                'palavras_chave' => ['activar', 'proxypay', 'configurar', 'credenciais'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como definir o valor das taxas de condomínio?',
                'resposta' => 'Há 2 níveis: (1) por imóvel (Imóveis, escolhe imóvel, Editar e Taxas de Condomínio mensais Kz); (2) regras gerais (Facturação, Configuração e Quotas).',
                'palavras_chave' => ['valor', 'taxa', 'definir', 'configurar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como configurar multas por atraso?',
                'resposta' => 'Em Facturação, Configuração e Multas. Escolhe tipo (percentual ou valor fixo), período de carência (dias após vencimento), e se é cumulativo. Sistema aplica automaticamente.',
                'palavras_chave' => ['multa', 'atraso', 'configurar', 'percentagem'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Posso desactivar geração automática de quotas?',
                'resposta' => 'Sim. Em Facturação, Configuração e Quotas usa o toggle Geração automática mensal. Útil em períodos de transição ou se quiseres controlo manual.',
                'palavras_chave' => ['desactivar', 'automático', 'manual', 'geração'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como adicionar/remover gestores ao condomínio?',
                'resposta' => 'Em Empresa e Condomínios geridos (admin-empresa), escolhe condomínio e Gestores. Adiciona/remove utilizadores com role gestor.',
                'palavras_chave' => ['gestor', 'adicionar', 'remover', 'permissão'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Como personalizar logo do condomínio?',
                'resposta' => 'Em Condomínios, escolhe condomínio e Editar. Secção Identidade visual. Carrega logo (PNG, máx 2MB). Aparece nos PDFs gerados (acta, recibo).',
                'palavras_chave' => ['logo', 'imagem', 'marca', 'identidade'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como configurar idioma/moeda?',
                'resposta' => 'Padrão: Português (Angola) e Kwanzas (Kz). Em Conta e Preferências podes escolher também Inglês ou Francês. Moeda é fixa em Kz (mercado angolano).',
                'palavras_chave' => ['idioma', 'moeda', 'português', 'kwanzas'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Posso definir notificações que recebo?',
                'resposta' => 'Sim. Em Conta e Notificações, escolhe canais (push, email, SMS) por tipo: pagamentos, pedidos, visitantes, avisos, assembleias.',
                'palavras_chave' => ['notificações', 'avisos', 'canais', 'preferências'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como configurar prazo de vencimento das taxas?',
                'resposta' => 'Em Facturação, Configuração e Quotas, no campo Dia de vencimento (dia do mês). Por exemplo, dia 8 = todas as taxas vencem dia 8 de cada mês.',
                'palavras_chave' => ['vencimento', 'prazo', 'dia', 'configurar'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como personalizar mensagens automáticas (lembretes)?',
                'resposta' => 'Em Configuração e Mensagens automáticas. Edita textos de: convite condómino, lembrete de pagamento, confirmação de pagamento, etc. Suporta variáveis ({nome}, {valor}).',
                'palavras_chave' => ['mensagens', 'templates', 'personalizar', 'lembretes'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como exportar dados do condomínio (backup)?',
                'resposta' => 'Em Configuração e Backup. Geras Excel/CSV com: condóminos, imóveis, lançamentos, pagamentos. Recomendado fazer backup mensal para arquivo próprio.',
                'palavras_chave' => ['backup', 'exportar', 'arquivo', 'dados'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como reverter a configuração de quotas se errar?',
                'resposta' => 'Em Facturação, Configuração e Quotas, antes de salvar, há botão Pré-visualizar impacto. Após salvar, podes Reverter última alteração (mantém histórico).',
                'palavras_chave' => ['reverter', 'desfazer', 'erro', 'configuração'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Como ver histórico de alterações de configuração?',
                'resposta' => 'Em Configuração e Histórico. Lista de todas as alterações feitas (quem, quando, antes/depois). Útil para auditoria e debug de problemas.',
                'palavras_chave' => ['histórico', 'auditoria', 'alterações', 'log'],
                'role_filter' => ['gestor'],
            ],
            [
                'pergunta' => 'Que é a Empresa Gestora?',
                'resposta' => 'É a entidade que contrata o ONDAKA e gere um ou mais condomínios. Pode ser uma empresa de gestão imobiliária ou um administrador profissional.',
                'palavras_chave' => ['empresa', 'gestora', 'contrata', 'administra'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como vejo o meu plano de subscrição?',
                'resposta' => 'Vai a Empresa e Subscrição. Vês plano actual, número de condomínios incluídos, recursos extra, data de renovação, e estado do pagamento.',
                'palavras_chave' => ['plano', 'subscrição', 'contrato', 'pacote'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Como adicionar novo condomínio à minha empresa?',
                'resposta' => 'Em Empresa, depois Condomínios e Novo condomínio. Indica nome, morada, NIF. Verifica que o teu plano permite adicionar mais (tens limite por subscrição).',
                'palavras_chave' => ['novo', 'adicionar', 'condomínio', 'empresa'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Que acontece se a subscrição expirar?',
                'resposta' => 'Tens 7 dias de tolerância. Após isso, app entra em modo limitado: condóminos podem ver dados mas não criar novos. Pagamento renova imediatamente.',
                'palavras_chave' => ['expirar', 'limite', 'renovar', 'tolerância'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Como comprar créditos SMS?',
                'resposta' => 'Em Empresa e Créditos SMS, clica em Comprar pacote. Pagamento por ProxyPay. Créditos usam-se em 2FA (login) e avisos urgentes.',
                'palavras_chave' => ['sms', 'créditos', 'comprar', 'pacote'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Como activar funcionalidades extra (loja interna)?',
                'resposta' => 'Em Empresa e Funcionalidades. Vês módulos disponíveis (ex: Lista Negra, Cadastro Funcionários). Cada um tem custo de activação + mensal. Activa apenas o que precisas.',
                'palavras_chave' => ['funcionalidades', 'extra', 'activar', 'módulo'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Como pagar a subscrição ONDAKA?',
                'resposta' => 'Em Empresa, Subscrição e Renovar. Recebes referência ProxyPay. Após pagamento (5 min), subscrição é estendida automaticamente.',
                'palavras_chave' => ['pagar', 'subscrição', 'renovar', 'ondaka'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Como ver facturas/recibos da minha subscrição?',
                'resposta' => 'Em Empresa e Facturação ONDAKA. Vês todas as facturas emitidas pelo Soluções Simples (operador da plataforma). Podes descarregar PDF.',
                'palavras_chave' => ['factura', 'recibo', 'soluções simples', 'pdf'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Como contactar suporte ONDAKA?',
                'resposta' => 'Email: suporte@ondaka.ao. Para questões urgentes, há também chat em ondaka.ao (canto inferior direito). Tempo médio de resposta: 4h em dias úteis.',
                'palavras_chave' => ['suporte', 'ajuda', 'contacto', 'email'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Posso transferir a empresa gestora para outro responsável?',
                'resposta' => 'Sim. O actual admin-empresa pode transferir titularidade em Empresa, Configuração e Transferir empresa. Requer confirmação por SMS e email.',
                'palavras_chave' => ['transferir', 'titularidade', 'novo dono', 'passar'],
                'role_filter' => ['admin-empresa'],
            ],
            [
                'pergunta' => 'Que é o Decreto Presidencial 141/15?',
                'resposta' => 'É o Decreto Presidencial n.º 141/15 de 29 de Junho de 2015, lei angolana que regulamenta a propriedade horizontal e a gestão de condomínios em Angola. ONDAKA está alinhado com este decreto.',
                'palavras_chave' => ['decreto', '141/15', 'lei', 'angola'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Que valor mínimo deve ter o Fundo de Reserva?',
                'resposta' => 'O Decreto 141/15 (Art. 7) define que o fundo de reserva deve ser pelo menos 10% do valor das quotas mensais. ONDAKA avisa quando a configuração está abaixo deste mínimo legal.',
                'palavras_chave' => ['fundo de reserva', 'mínimo', '10%', 'decreto'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Há limite máximo para a quota de condomínio (UCF/m²)?',
                'resposta' => 'Sim. O Decreto 141/15 estabelece limites em UCF/m² (Unidade de Cálculo de Facturação) para evitar abusos. Os valores dependem do tipo de condomínio e estão tabelados.',
                'palavras_chave' => ['limite', 'ucf', 'm2', 'máximo'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'A acta da assembleia tem força de título executivo?',
                'resposta' => 'Sim. Decreto 141/15, Art. 12: a acta da assembleia constitui título executivo para cobrança coerciva de quotas em dívida. Permite acção judicial mais célere.',
                'palavras_chave' => ['título executivo', 'acta', 'cobrança', 'judicial'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Quais documentos o administrador é obrigado a manter?',
                'resposta' => 'Decreto 141/15, Arts. 13-15: actas de assembleia, contas mensais, orçamento anual, regulamento, seguros, e contratos com prestadores. Tudo deve estar acessível para consulta dos condóminos.',
                'palavras_chave' => ['documentos', 'obrigatório', 'administrador', 'arquivo'],
                'role_filter' => ['administrador-condominio'],
            ],
            [
                'pergunta' => 'Como é eleito o administrador do condomínio?',
                'resposta' => 'Decreto 141/15, Art. 5: o administrador é eleito em assembleia geral ordinária por maioria simples (mais de 50% das milésimas presentes). Mandato é tipicamente 1 ano, renovável.',
                'palavras_chave' => ['eleger', 'administrador', 'mandato', 'eleição'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Posso recusar pagar quotas se discordo da gestão?',
                'resposta' => 'Não. As quotas são obrigação legal independente de discordância. Para questionar gestão, usa assembleia (votar contra orçamento, propor mudanças). Não pagar gera juros, multas e acção judicial.',
                'palavras_chave' => ['recusar', 'não pagar', 'obrigação', 'discordância'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Quem responde por dívidas do condomínio?',
                'resposta' => 'Cada condómino responde pela sua quota proporcional. Em casos de obras urgentes ou despesas comuns aprovadas em assembleia, a responsabilidade é solidária pela quota proporcional de cada um.',
                'palavras_chave' => ['dívida', 'responsabilidade', 'solidária', 'condóminos'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Posso vender o meu imóvel se devo quotas?',
                'resposta' => 'Podes, mas a dívida acompanha o imóvel (Decreto 141/15). O comprador pode exigir certidão de dívidas e descontar do preço, ou tu deves regularizar antes da escritura.',
                'palavras_chave' => ['vender', 'dívida', 'escritura', 'comprador'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Como obter certidão de dívidas para escritura?',
                'resposta' => 'Pede ao gestor: vai a Pedidos e Novo pedido com título Certidão de dívidas. O gestor gera documento PDF com extracto de obrigações pagas e em dívida do teu imóvel.',
                'palavras_chave' => ['certidão', 'dívidas', 'escritura', 'cartório'],
                'role_filter' => ['condomino'],
            ],
            [
                'pergunta' => 'Que é o ONDAKA?',
                'resposta' => 'ONDAKA é a primeira plataforma SaaS de gestão de condomínios feita 100% para Angola. Inclui: facturação automática, pagamentos digitais, pré-aprovação de visitas, encomendas, assembleias com voto remoto, conformidade com Decreto 141/15.',
                'palavras_chave' => ['ondaka', 'que é', 'plataforma', 'angola'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Quem desenvolveu o ONDAKA?',
                'resposta' => 'ONDAKA é desenvolvido pela Soluções Simples, Lda. — empresa angolana focada em soluções digitais para o mercado local. Sede em Luanda.',
                'palavras_chave' => ['soluções simples', 'empresa', 'desenvolvedor', 'quem'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Os meus dados estão seguros?',
                'resposta' => 'Sim. Dados em servidores com encriptação, backup diário, conformidade com Lei de Protecção de Dados Pessoais. 2FA SMS disponível. Apenas tu e os roles autorizados (gestor, administrador) acedem aos teus dados.',
                'palavras_chave' => ['segurança', 'dados', 'privacidade', 'protecção'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'A app mobile está disponível para iPhone e Android?',
                'resposta' => 'Sim. Procura ONDAKA na App Store (iOS) ou Google Play (Android). Versão web disponível em ondaka.ao para qualquer browser.',
                'palavras_chave' => ['app', 'mobile', 'android', 'iphone'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Posso sugerir uma nova funcionalidade?',
                'resposta' => 'Sim! Adoramos sugestões. Manda email para ideias@ondaka.ao ou usa o chat de suporte. Avaliamos todas as sugestões e priorizamos as mais pedidas no roadmap.',
                'palavras_chave' => ['sugestão', 'ideia', 'funcionalidade', 'roadmap'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],
            [
                'pergunta' => 'Como dar feedback sobre o ONDAKA?',
                'resposta' => '3 vias: (1) chat em ondaka.ao, (2) email feedback@ondaka.ao, (3) avaliação na App Store / Google Play. Toda opinião é bem-vinda — ajuda-nos a melhorar para os condóminos angolanos.',
                'palavras_chave' => ['feedback', 'opinião', 'avaliar', 'comentar'],
                'role_filter' => ['condomino', 'gestor', 'administrador-condominio', 'admin-empresa', 'funcionario', 'prestador'],
            ],

        ];
    }
}
